# -*- coding: utf-8 -*-
"""Building your first bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRY6tbza9FPOeZwDPcfLoJS1Td17PfND

**type of chat boot** two type
 
1. Generative

2. retrieval

**type of question**

1.open domain 

2.close domain
"""

# Load data preprocessing libs
import pandas as pd
import numpy as np

# Load vectorizer and similarity measure
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""## Read the data"""

# Read data and drop examples that has no answer
df = pd.read_csv("aws_faq.csv")
df.dropna(inplace=True)

"""## Train the vectorizer"""

vectorizer = TfidfVectorizer()
vectorizer.fit(np.concatenate((df.Question, df.Answer)))

"""## Vectorize questions"""

Question_vectors = vectorizer.transform(df.Question)

"""## Chat with the user"""

print("You can start chatting with me now.")
while True:
    # Read user input
    input_question = input()

    # Locate the closest question
    input_question_vector = vectorizer.transform([input_question])

    # Compute similarities
    similarities = cosine_similarity(input_question_vector, Question_vectors)

    # Find the closest question
    closest = np.argmax(similarities, axis=1)

    # Print the correct answer
    print("BOT: " + df.Answer.iloc[closest].values[0])

